((higher-education (((title "System Analyst")
                     (institution "CAECE University")
                     (startDate "2010")
                     (endDate "2014"))
                    ((title "System Engineering")
                     (institution "Universidad Tecnologica Nacional")
                     (startDate "2005")
                     (endDate "2010")
                     (comments "(Unfinished)"))))
 (other-education (((date "2013")
                    (title "Image and video processing: From Mars to Hollywood with a stop at the hospital")
                    (where "Coursera"))
                   ((date "2012")
                    (title "Algorithms: Design and Analysis Part I")
                    (where "Coursera"))
                   ((date "2011")
                    (title "Programación de Seguridad mediante Bibliotecas")
                    (where "ECI 2011 (UBA)"))
                   ((date "2011")
                    (title "Programación distribuida y paralela usando MPI")
                    (where "ECI 2011 (UBA)"))
                   ((date "2010") (title "C++ Internals") (where "FuDePAN"))
                   ((date "2010") (title "C/C++ Good Practices") (where "FuDePAN"))))
 (positions (((company "Jampp")
              (title "Sr. Python Developer")
              (startDate "01/2015")
              (endDate "06/2015"))
             ((company "bevuta IT GmbH")
              (title "Scheme Developer")
              (startDate "02/2013")
              (endDate "02/2015")
              (keywords ("android" "scheme" "chicken scheme" "C" "jni")))
             ((company "FuDePAN")
              (startDate "08/2010")
              (endDate "01/2014")
              (title "C++ Developer (Ad honorem)")
              (summary "Bioinformatics oriented tools development.")
              (keywords ("C++" "Template Metaprogramming" "googletest"
                         "googlemock" "g++" "make" "Scons" "Jenkins"
                         "SVN" "Mercurial")))
             ((company "LambdaDev")
              (title "Freelance Software Engineer/Developer")
              (startDate "07/2010")
              (keywords ("C++" "Python" "Java" "SOAP" "suds" "Scrapy" "Webpy" "Pylons"
                         "Google Apps Engine" "Spring" "Hibernate" "JPA2" "Maven" "Javascript" "Dojo"
                         "jQuery" "MySQL" "PostgreSQL" "bash" "bash scripting" "SVN" "Mercurial" "Git")))
             ((company "FuDePAN")
              (title "Regional Coordinator for Buenos Aires (Ad honorem)")
              (endDate "01/2013")
              (startDate "07/2011")
              (summary "Projects and volunteers coordination"))
             ((company "CITEDEF")
              (title "Becario / Groovy-Grails Developer")
              (endDate "08/2011")
              (startDate "04/2011")
              (summary "Sistema CRISIS"))
             ((company "TeraCode")
              (title "Ssr. Python Developer")
              (endDate "01/2011")
              (startDate "04/2010")
              (summary "Working in performable's web-site/platform")
              (keywords ("python" "Tornado" "django" "SQLAlchemy" "jQuery" "MySQL" "Scrum")))
             ((company "Livra")
              (endDate "04/2010")
              (startDate "04/2008")
              (title "Ssr. Java Developer")
              (summary "Livra’s portal and online marketing tools (surveys, statistics, etc).")
              (keywords ("Apache Wicket" "Hibernate" "JUnit" "Velocity"
                         "Lucene" "PostgreSQL" "Web Services" "Rest"
                         "Jersey" "SOAP" "Axis" "prototype" "scriptaculous"
                         "Eclipse" "Tomcat" "Jetty" "ant" "Maven" "SVN")))
             ((company "Thales Information Systems")
              (title "Java Developer")
              (startDate "08/2007")
              (endDate "04/2008")
              (summary "Developer in Thales Software Factory. IVR using avaya tools and Asterix. Web-based tools using structs, hibernate and spring."))
             ((company "Star Technology")
              (title "Developer")
              (startDate "06/2006")
              (endDate "12/2006")
              (keywords ("SQL" "PL/SQL" "Oracle Financials" "Reports Builder" "Forms Builder")))))
 (publications (((authors "Hugo Arregui, Carlos Castro, Daniel Gutson")
                 (date "2012")
                 (title "Curiously Recursive Template Problems with Aspect Oriented Programming")
                 (where "ACCU Overload magazine 109, June 2012."))
                ((authors "Hugo Arregui, Daniel Gutson")
                 (date "2011")
                 (title "Biopp2: biological alphabet manipulation library")
                 (where "2do Congreso Argentino de Biologia Computacional"))
                ((authors 
                   "Hugo Arregui, Rodrigo Castaño, Lucía Lauría, Rafael Garabato, Elmer Fernández, Marcos Villarreal")
                 (date "2011")
                 (title "Backbones Generator v2")
                 (where "2do Congreso Argentino de Biologia Computacional"))))
 (skills (("Languages" ("C++" "Python" "Java" "Scheme" "Bash Scripting/AWK" "JavaScript" "Groovy"))
          ("Python tools" ("django" "pylons" "tornado" "webpy" "unittest" "pymock" "flake8" "flask"))
          ("C++ tools" ("googletest" "googlemock"))
          ("Java tools" ("Hibernate" "Spring" "Struts" "Wicket" "Junit"))
          ("Javascript tools" ("jQuery" "Dojo" "Prototype"))
          ("Others tools" ("valgrind" "gdb" "Vim" "Eclipse" "Youtrack" "Google Code"
                           "Redmine" "Bitbucket" "Gitlab" "GitHub" "Asana" "Bootstrap"
                           "Android"))
          ("Version Control" ("hg" "git" "svn"))
          ("Build Systems" ("make" "scons" "ant"))
          ("Databases" ("PostgreSQL" "MySQL" "SQL Server" "Oracle"))
          ("Continuous integration" ("Jenkins/Hudson"))
          ("Operating Systems" ("Unix/Linux" "Windows")))))

