((higher-education (((title "System Analyst")
                     (institution "CAECE University")
                     (startDate "2010")
                     (endDate "2014"))
                    ((title "System Engineering")
                     (institution "Universidad Tecnologica Nacional")
                     (startDate "2005")
                     (endDate "2010")
                     (comments "(Unfinished)"))))
 (other-education (((date "2013")
                    (title "Image and video processing: From Mars to Hollywood with a stop at the hospital")
                    (where "Coursera"))
                   ((date "2012")
                    (title "Algorithms: Design and Analysis Part I")
                    (where "Coursera"))
                   ((date "2011")
                    (title "Programación de Seguridad mediante Bibliotecas")
                    (title-en "Security programming using libraries")
                    (where "ECI 2011 (UBA)"))
                   ((date "2011")
                    (title "Programación distribuida y paralela usando MPI")
                    (title-en "Distributed and parallel programming using MPI")
                    (where "ECI 2011 (UBA)"))
                   ((date "2010") (title "C++ Internals") (where "FuDePAN"))
                   ((date "2010") (title "C/C++ Good Practices") (where "FuDePAN"))))
 (positions (((company "Auth0")
              (company-website "https://auth0.com/")
              (title "Engineer")
              (startDate "03/2016")
              (keywords ("node" "express" "jwt" "elasticsearch" "mongo" "hapi")))
             ((company "LambdaDev")
              (title "Freelance Software Engineer/Developer")
              (startDate "07/2010")
              (keywords ("C++" "Python" "Java" "JavaScript" "Bash" "clojure" "clojurescript"
                         "scrapy" "web.py" "Flask" "pyramid" "django"
                         "jQuery" "Dojo"
                         "Mercurial" "Git" "SVN" 
                         "MySQL" "PostgreSQL" 
                         "bash scripting" 
                         "phonegap / cordova"
                         "SOAP" "suds" "Google Apps Engine" "Spring" "Hibernate" "JPA2" "JNI" "Maven")))
             ((company "Jampp")
              (company-website "http://jampp.com/")
              (title "Senior Python Developer")
              (startDate "01/2015")
              (endDate "06/2015")
              (keywords ("zeromq" "sklearn" "pandas" "numpy" "marchine learning")))
             ((company "bevuta IT GmbH")
              (summary "Android development using java + chicken scheme + jni")
              (company-website "http://www.bevuta.com/en/")
              (title "Scheme Developer")
              (startDate "02/2013")
              (endDate "02/2015")
              (keywords ("android" "scheme" "chicken scheme" "C" "jni")))
             ((company "FuDePAN")
              (startDate "08/2010")
              (endDate "01/2014")
              (title "C++ Developer (Ad honorem)")
              (summary "Bioinformatics oriented tools development.")
              (keywords ("C++" "Template Metaprogramming" "googletest"
                         "googlemock" "g++" "make" "Scons" "Jenkins"
                         "SVN" "Mercurial")))
             ((company "FuDePAN")
              (title "Regional Coordinator for Buenos Aires (Ad honorem)")
              (endDate "01/2013")
              (startDate "07/2011")
              (summary "Projects and volunteers coordination"))
             ; ((company "CITEDEF")
             ;  (title "Becario / Groovy-Grails Developer")
             ;  (endDate "08/2011")
             ;  (startDate "04/2011")
             ;  (summary "Sistema CRISIS"))
             ((company "TeraCode")
              (company-website "http://teracode.com/")
              (title "Ssr. Python Developer")
              (endDate "01/2011")
              (startDate "04/2010")
              (summary "Working in performable's web-site/platform")
              (keywords ("python" "Tornado" "django" "SQLAlchemy" "jQuery" "MySQL" "Scrum")))
             ((company "Livra")
              (company-website "http://www.livra.com/")
              (endDate "04/2010")
              (startDate "04/2008")
              (title "Ssr. Java Developer")
              (summary "Develop Livra’s website. Creating and maintaining marketing tools for surveys, statistics, etc.")
              (keywords ("java" "Apache Wicket" "wicket" "Hibernate" "JUnit" "Velocity"
                         "Lucene" "PostgreSQL" "Web Services" "Rest"
                         "Jersey" "SOAP" "Axis" "prototype" "scriptaculous"
                         "Eclipse" "Tomcat" "Jetty" "ant" "Maven" "SVN")))
             ((company "Thales Information Systems")
              (title "Java Developer")
              (startDate "08/2007")
              (endDate "04/2008")
              (summary "Create an IVR using avaya software and Asterix for a prestigious bank. Create and support web-based tools using structs, hibernate and spring.")
              (keywords ("IVR" "asterix" "structs" "hibernate" "spring")))
             ; ((company "Star Technology")
             ;  (title "Developer")
             ;  (startDate "06/2006")
             ;  (endDate "12/2006")
             ;  (keywords ("SQL" "PL/SQL" "Oracle Financials" "Reports Builder" "Forms Builder")))
             ))
 (publications (((authors "Hugo Arregui, Carlos Castro, Daniel Gutson")
                 (date "2012")
                 (title "Curiously Recursive Template Problems with Aspect Oriented Programming")
                 (article-link "http://accu.org/index.php/journals/1916")
                 (where "ACCU Overload magazine 109, June 2012."))
                ((authors "Hugo Arregui, Daniel Gutson")
                 (date "2011")
                 (title "Biopp2: biological alphabet manipulation library")
                 (where "2do Congreso Argentino de Biologia Computacional"))
                ((authors 
                   "Hugo Arregui, Rodrigo Castaño, Lucía Lauría, Rafael Garabato, Elmer Fernández, Marcos Villarreal")
                 (date "2011")
                 (title "Backbones Generator v2")
                 (where "2do Congreso Argentino de Biologia Computacional"))))
 (skills (("Languages" ("C++" "Python" "Java" "Scheme" "Bash Scripting/AWK" "JavaScript" "Groovy" "Ruby" "NodeJS"))
          ("Python tools" ("django" "pylons" "tornado" "webpy" "unittest" "pymock" "flake8" "flask"))
          ("C++ tools" ("googletest" "googlemock"))
          ("NodeJS tools" ("restify" "express" "hapi" "lodash"))
          ("Ruby tools" ("sinatra" "sequel"))
          ("Java tools" ("Hibernate" "Spring" "Struts" "Wicket" "Junit"))
          ("Javascript tools" ("jQuery" "Dojo" "Prototype" "lodash"))
          ("Mobile" ("Android" "phonegap/cordova"))
          ("Others tools" ("valgrind" "gdb" "Vim" "Eclipse" "Youtrack" "Google Code" "redis"
                           "Redmine" "Bitbucket" "Gitlab" "GitHub" "Asana" "Bootstrap" "ElasticSearch"))
          ("Version Control" ("hg" "git" "svn"))
          ("Build Systems" ("make" "scons" "ant"))
          ("Databases" ("PostgreSQL" "MySQL" "SQL Server" "Oracle" "MongoDB"))
          ("Continuous integration" ("Jenkins/Hudson"))
          ("Operating Systems" ("Unix/Linux" "Windows")))))

